#!/usr/bin/env python3
"""Generate `unifi-map.1` from the argument parser.

Committed, so a clone has a man page without a build step, and regenerated by
`make docs` with `make check` failing if it is stale. Hand-writing one
guarantees it goes out of date, which is worse than not having it.

`argparse-manpage` was tried first and dropped. It works, but its API takes a
parser and little else, and two things it cannot do are the two that matter
here: every global option is attached to every subparser via `parents=`, so it
printed all fifteen of them three times over, and there is no way to add the
sections that make a man page worth opening. ENVIRONMENT, FILES, EXAMPLES and
the note about support files are not derivable from a parser; they are the
reason somebody reaches for `man` instead of `--help`.

So the flags come from the parser and the prose lives below. Those are the two
halves a man page needs, and only one of them can be generated.

The date in the header comes from the changelog entry for the current version,
not from the clock. Using today's date would rewrite the file on any day it was
regenerated and fail the staleness check for no reason.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _cli_introspect import (
    ROOT,
    build_parser,
    command_groups,
    options,
    positionals,
    release_date,
    subcommands,
)

from unifi_map import __version__

PAGE = ROOT / "unifi-map.1"


def esc(text: str) -> str:
    r"""Escape for roff.

    A backslash starts an escape, and a line whose first character is `.` or `'`
    is read as a request rather than as text. A hyphen is rendered as a soft
    typographic dash unless escaped, which quietly makes every flag in the page
    uncopyable.
    """
    text = text.replace("\\", "\\e").replace("-", r"\-")
    if text.startswith((".", "'")):
        text = "\\&" + text
    return text


def option_block(items) -> list[str]:
    out = []
    for option in items:
        names = ", ".join(f"\\fB{esc(n)}\\fR" for n in option.names)
        if option.argument:
            names += f" \\fI{esc(option.argument)}\\fR"
        out += [".TP", names, esc(option.help)]
        # Several help strings already end in "(default: X)", which reads well
        # in a terminal. Appending our own line there gives "(default: cache)
        # Default: cache." Only add it when the help does not say so itself.
        if option.default and "default" not in option.help.lower():
            out.append(f"Default: \\fB{esc(option.default)}\\fR.")
    return out


def _command_block(parser) -> list[str]:
    """One entry per subcommand, from its own help text."""
    action = next(a for a in parser._actions if a.__class__.__name__ == "_SubParsersAction")
    described = {c.dest: c.help for c in action._choices_actions}
    out = []
    for name in subcommands(parser):
        out += [".TP", f"\\fB{esc(name)}\\fR", esc(described.get(name) or name)]
    return out


def render() -> str:
    parser = build_parser()
    date = release_date(__version__)

    lines = [
        f'.TH UNIFI\\-MAP 1 "{date}" "unifi\\-map {esc(__version__)}" "User Commands"',
        ".SH NAME",
        "unifi\\-map \\- export a UniFi network topology as vector diagrams",
        ".SH SYNOPSIS",
        ".B unifi\\-map",
        "[\\fIglobal options\\fR]",
        "|".join(f"\\fB{esc(name)}\\fR" for name in subcommands(parser)),
        "[\\fIcommand options\\fR]",
        ".SH DESCRIPTION",
        "The UniFi Network web interface has no topology export, and a screenshot",
        "cannot substitute for one: the topology view is a fixed viewport wrapping a",
        "pan and zoom canvas, so a full\\-page capture returns only the visible region,",
        "and zooming out far enough to fit the network is what makes the labels",
        "unreadable.",
        ".PP",
        "\\fBunifi\\-map\\fR reads the same JSON endpoints the interface draws from and",
        "renders them properly: SVG and PDF that stay sharp at any zoom, PNG, Graphviz",
        "source, draw.io files whose shapes are already positioned, Mermaid for a",
        "README or a wiki, and JSON of the normalised topology for other programs.",
        ".PP",
        "It only ever reads. Every request is a GET, and there is no code path that",
        "changes anything on the controller.",
        ".SS Two stages",
        "\\fBfetch\\fR caches the controller's JSON; \\fBrender\\fR turns that cache into",
        "diagrams; \\fBall\\fR does both. They are separable so a map can be restyled",
        "repeatedly without touching the controller again, and so each cached snapshot",
        "is a record of the network at one moment.",
        ".SS Without a controller",
        "\\fB\\-\\-support\\-file\\fR reads a console support file instead, which needs no",
        "credentials and contacts no controller. Rendering afterwards still fetches",
        "artwork unless \\fB\\-\\-offline\\fR or \\fB\\-\\-icons builtin\\fR is given.",
        ".PP",
        "A support file is not safe to pass around. It is a complete inventory of the",
        "network: every MAC, hostname, address and lease, the SSIDs and subnets, the",
        "WAN addresses, and logs of client activity. UniFi redacts some credential",
        "fields by name and that pass is demonstrably incomplete. Treat one as a",
        "secret and delete it when finished.",
        ".SH COMMANDS",
        # From the parser, because a hand-written list here fell two commands
        # behind without anything noticing.
        *_command_block(parser),
        ".SH GLOBAL OPTIONS",
        "Accepted before or after the subcommand, so",
        "\\fBunifi\\-map all \\-\\-support\\-file\\fR \\fIF\\fR and",
        "\\fBunifi\\-map \\-\\-support\\-file\\fR \\fIF\\fR \\fBall\\fR are equivalent.",
        *option_block(options(parser)),
    ]

    subs = subcommands(parser)
    for names, unique in command_groups(parser):
        listed = " and ".join(n.upper() for n in names)
        unique = positionals(subs[names[0]]) + list(unique)
        if not unique:
            lines += [
                f".SH {listed} OPTIONS",
                f"\\fB{esc(names[0])}\\fR takes only the global options above.",
            ]
            continue
        lines += [f".SH {listed} OPTIONS", *option_block(unique)]

    lines += [
        ".SH ENVIRONMENT",
        ".TP",
        "\\fBUNIFI_HOST\\fR",
        "Hostname or address of the console. Required for a live fetch.",
        ".TP",
        "\\fBUNIFI_API_KEY\\fR",
        "An API key. Required for a live fetch. A key carries the permissions of the",
        "account that created it; UniFi offers no way to issue a read\\-only one.",
        ".TP",
        "\\fBUNIFI_SITE\\fR",
        "Which site to read. Overridden by \\fB\\-\\-site\\fR. Defaults to",
        "\\fBdefault\\fR.",
        ".TP",
        "\\fBUNIFI_VERIFY_TLS\\fR",
        "\\fBtrue\\fR, \\fBfalse\\fR, or a path to a CA bundle.",
        ".TP",
        "\\fBUNIFI_MAP_ENV\\fR",
        "Path to a credential file, tried before the default locations.",
        ".PP",
        "The \\fBUDM_\\fR\\fI*\\fR spellings of these are deprecated and warn once per",
        "run. A key is never written into the environment, and is removed from the",
        "environment Graphviz is run with.",
        ".SH FILES",
        ".TP",
        "\\fB.env\\fR, \\fB~/.config/unifi\\-map/env\\fR",
        "Credential files, searched in that order after \\fB\\-\\-env\\-file\\fR and",
        "\\fBUNIFI_MAP_ENV\\fR. Create with \\fBinstall \\-m 600\\fR: a plain copy",
        "inherits the umask and usually leaves an API key world\\-readable.",
        "\\fBunifi\\-map\\fR warns when it reads one others can see.",
        ".TP",
        "\\fBcache/\\fR",
        "Cached snapshots. A full inventory of MACs, hostnames and addresses.",
        "Written mode 0600. Do not commit one or attach it to an issue.",
        ".TP",
        "\\fBcache/assets/\\fR",
        "Downloaded artwork, kept apart from snapshots so a read\\-only snapshot",
        "directory stays clean.",
        ".TP",
        "\\fBoverrides.toml\\fR",
        "Manual corrections, read automatically when present in the working",
        "directory. See \\fB\\-\\-overrides\\fR.",
        ".SH EXAMPLES",
        ".TP",
        "Fetch and render with the defaults:",
        "\\fBunifi\\-map all\\fR",
        ".TP",
        "Restyle without touching the controller again:",
        "\\fBunifi\\-map render \\-\\-layout tree \\-\\-theme dark\\fR",
        ".TP",
        "Map from a support file, contacting nothing at all:",
        "\\fBunifi\\-map \\-\\-support\\-file\\fR \\fIsupport.tgz\\fR",
        "\\fBall \\-\\-offline\\fR",
        ".TP",
        "Produce a diagram safe to publish:",
        "\\fBunifi\\-map render \\-\\-obfuscate\\fR",
        ".TP",
        "One diagram per client network:",
        "\\fBunifi\\-map render \\-\\-per\\-network\\fR",
        ".SH EXIT STATUS",
        ".TP",
        "\\fB0\\fR",
        "Success.",
        ".TP",
        "\\fB1\\fR",
        "The controller, a support file, Graphviz or an output path failed.",
        ".TP",
        "\\fB2\\fR",
        "Configuration or command line error.",
        ".TP",
        "\\fB3\\fR",
        "Graphviz is not installed. Distinct from \\fB1\\fR because it is fixed by",
        "installing a package rather than by changing anything here, and because",
        "\\fBdot\\fR, \\fBmermaid\\fR and \\fBjson\\fR do not need it at all.",
        ".SH SEE ALSO",
        "\\fBdot\\fR(1), \\fBunflatten\\fR(1)",
        ".PP",
        "Full documentation, including the overrides format and the security notes",
        "summarised here: \\fIhttps://github.com/gitkodak/unifi\\-map\\fR",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if PAGE.is_file() and PAGE.read_text(encoding="utf-8") == text:
        print(f"{PAGE.name} is current.")
        return 0
    PAGE.write_text(text, encoding="utf-8")
    print(f"{PAGE.name} updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
